import { ArrowRight, ChefHat, HeartHandshake, Leaf, Sparkles, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import PageHero from '../components/PageHero'

const values = [[Leaf,'Fresh by nature','Vegetarian food built around honest ingredients and expressive flavour.'],[HeartHandshake,'Warm by instinct','Hospitality that feels attentive, easy and genuinely personal.'],[Sparkles,'Elevated everyday','The comfort you know, presented with thought and a little theatre.']]

export default function About() {
  return <><PageHero eyebrow="The Corn Bite story" title="A restaurant built around the feeling of coming home." text="Not just a place to eat—a place to pause, reconnect, and leave with one more shared memory."/>
    <section className="py-28"><div className="shell grid gap-14 lg:grid-cols-2 lg:items-center"><div data-cinema="left" className="image-luxury relative min-h-[580px] overflow-hidden rounded-[2.25rem]"><img src="/images/restaurant-hero.png" alt="The warm Corn Bite dining room" className="absolute inset-0 h-full w-full object-cover object-right"/><div className="absolute inset-0 bg-gradient-to-t from-[#100d0a] via-transparent to-transparent"/><div className="glass-card absolute bottom-6 left-6 right-6 p-6"><span className="text-xs uppercase tracking-[.2em] text-amber-300">Since 2018</span><p className="mt-2 font-display text-2xl">A neighbourhood table with a modern soul.</p></div></div><div data-cinema="right"><p className="eyebrow-warm">Why we began</p><h2 className="font-display text-5xl leading-[1.02] sm:text-6xl">Great food brings people closer.</h2><p className="mt-7 text-base leading-8 text-muted">Corn Bite began with one simple idea: vegetarian dining should feel abundant, exciting and deeply welcoming. A family lunch should have room to linger. A coffee should make conversation stretch. A celebration should feel effortless.</p><p className="mt-5 text-base leading-8 text-muted">That belief still shapes every plate, every greeting and every corner of our dining room.</p><Link to="/reserve" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-amber-300">Experience Corn Bite <ArrowRight size={16}/></Link></div></div></section>
    <section className="border-y border-white/[.06] bg-[#0c0a08] py-28"><div className="shell"><div data-cinema className="mx-auto max-w-3xl text-center"><ChefHat className="mx-auto text-amber-300"/><h2 className="mt-8 font-display text-5xl sm:text-6xl">Our promise is felt,<br/><em className="text-amber-200">not announced.</em></h2></div><div className="mt-16 grid gap-5 md:grid-cols-3">{values.map(([Icon,title,text],index)=><article key={title} data-cinema style={{'--cinema-delay':`${index*100}ms`}} className="glass-card min-h-[310px] p-8"><Icon className="text-amber-300"/><span className="mt-20 block text-[10px] tracking-[.2em] text-white/25">0{index+1}</span><h3 className="mt-3 font-display text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-muted">{text}</p></article>)}</div></div></section>
    <section className="py-28"><div className="shell"><div data-cinema="scale" className="glass-card grid gap-8 p-8 sm:p-12 md:grid-cols-[auto_1fr_auto] md:items-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-orange-500 to-amber-300 text-[#1b1008]"><UsersRound size={28}/></span><div><p className="eyebrow-warm mb-2">There’s always room</p><h2 className="font-display text-3xl sm:text-4xl">Bring the people who make the meal matter.</h2></div><Link to="/reserve" className="btn-warm">Reserve a table <ArrowRight size={17}/></Link></div></div></section>
  </>
}
