import { LockKeyhole, Mail, Phone, UserRound } from 'lucide-react'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import AuthShell, { PasswordHint } from '../components/AuthShell'
import { useAuth } from '../context/AuthContext'
import { isSupabaseConfigured, requireSupabase } from '../lib/supabase'

const initial={fullName:'',phone:'',email:'',password:'',confirmPassword:''}
export default function CustomerSignup(){
  const {user,isAdmin,loading:sessionLoading}=useAuth();const [form,setForm]=useState(initial);const [loading,setLoading]=useState(false);const [pendingEmail,setPendingEmail]=useState('');const navigate=useNavigate();const update=e=>setForm(f=>({...f,[e.target.name]:e.target.value}))
  if(!sessionLoading&&user)return <Navigate to={isAdmin?'/admin':'/account'} replace/>
  async function submit(event){event.preventDefault();if(form.password!==form.confirmPassword)return toast.error('Passwords do not match.');if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(form.password))return toast.error('Password does not meet the security requirements.');if(!/^\+?[0-9\s-]{10,15}$/.test(form.phone))return toast.error('Enter a valid phone number.');setLoading(true);try{const client=requireSupabase();const {data,error}=await client.auth.signUp({email:form.email.trim(),password:form.password,options:{data:{full_name:form.fullName.trim(),phone:form.phone.trim()},emailRedirectTo:`${window.location.origin}/account`}});if(error)throw error;if(data.user?.identities?.length===0)throw new Error('An account with this email already exists.');if(data.session){toast.success('Account created. Welcome!');navigate('/account')}else setPendingEmail(form.email.trim())}catch(error){toast.error(error.message)}finally{setLoading(false)}}
  if(pendingEmail)return <AuthShell title="Check your inbox" text={`We sent a confirmation link to ${pendingEmail}. Open it to activate your customer account.`}><Link to="/customer/login" className="btn-primary w-full">Return to login</Link></AuthShell>
  return <AuthShell title="Create an account" text="Your password is handled only by Supabase Auth and is never stored by Corn Bite." footer={<>Already registered? <Link className="font-semibold text-lime hover:underline" to="/customer/login">Customer Login</Link></>}><form onSubmit={submit} className="space-y-4"><label><span className="label">Full name</span><div className="relative"><UserRound className="absolute left-4 top-3.5 text-muted" size={17}/><input required minLength="2" maxLength="80" name="fullName" autoComplete="name" className="input pl-11" value={form.fullName} onChange={update} placeholder="Your full name"/></div></label><label><span className="label">Phone number</span><div className="relative"><Phone className="absolute left-4 top-3.5 text-muted" size={17}/><input required name="phone" inputMode="tel" autoComplete="tel" className="input pl-11" value={form.phone} onChange={update} placeholder="+91 98765 43210"/></div></label><label><span className="label">Email</span><div className="relative"><Mail className="absolute left-4 top-3.5 text-muted" size={17}/><input required name="email" type="email" autoComplete="email" className="input pl-11" value={form.email} onChange={update} placeholder="you@example.com"/></div></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Password</span><div className="relative"><LockKeyhole className="absolute left-4 top-3.5 text-muted" size={17}/><input required name="password" type="password" autoComplete="new-password" className="input pl-11" value={form.password} onChange={update}/></div></label><label><span className="label">Confirm password</span><input required name="confirmPassword" type="password" autoComplete="new-password" className="input" value={form.confirmPassword} onChange={update}/></label></div><PasswordHint/><button disabled={loading||!isSupabaseConfigured} className="btn-primary !mt-6 w-full">{loading?'Creating account…':'Create Customer Account'}</button></form></AuthShell>
}
