import { CalendarCheck, Check, ChevronRight, Clock3, LayoutDashboard, LogOut, RefreshCw, Search, UsersRound, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import Brand from '../components/Brand'
import TableGrid, { TableLegend } from '../components/TableGrid'
import { useAuth } from '../context/AuthContext'
import { requireSupabase } from '../lib/supabase'

const activeStatuses = ['pending','confirmed','arrived','occupied']
const badge = { pending:'bg-amber-400/10 text-amber-300',confirmed:'bg-sky-400/10 text-sky-300',arrived:'bg-red-400/10 text-red-300',occupied:'bg-red-400/10 text-red-300',completed:'bg-emerald-400/10 text-emerald-300',cancelled:'bg-white/5 text-muted' }

function ReservationCard({ reservation, onAction, updating }) {
  const next = reservation.status==='pending'?['Confirm','confirmed']:reservation.status==='confirmed'?['Arrived','occupied']:['Complete','completed']
  const isActive=activeStatuses.includes(reservation.status)
  return <article className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-3"><h3 className="font-semibold">{reservation.customer_name}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${badge[reservation.status]}`}>{reservation.status}</span></div><p className="mt-1 text-xs text-muted">{reservation.reservation_id} · {reservation.phone}</p></div><div className="rounded-xl bg-lime/10 px-3 py-2 text-center text-lime"><strong className="block">T{reservation.table_number}</strong><span className="text-[9px] uppercase">Table</span></div></div><div className="mt-5 grid grid-cols-3 gap-3 rounded-xl bg-white/[.025] p-3 text-xs"><span><small className="block text-muted">Date</small>{reservation.booking_date}</span><span><small className="block text-muted">Time</small>{reservation.booking_time.slice(0,5)}</span><span><small className="block text-muted">Party</small>{reservation.guests} guests</span></div>{isActive&&<div className="mt-4 flex gap-2"><button disabled={updating} onClick={()=>onAction(reservation.id,next[1])} className="btn-primary !min-h-9 flex-1 !px-3 !py-2 !text-xs">{next[0]} <ChevronRight size={14}/></button><button disabled={updating} onClick={()=>onAction(reservation.id,'cancelled')} className="grid h-9 w-9 place-items-center rounded-full border border-white/10 text-muted hover:border-red-400/40 hover:text-red-300" aria-label="Cancel reservation"><X size={15}/></button></div>}</article>
}

export default function Dashboard(){
  const {user}=useAuth();const [reservations,setReservations]=useState([]);const [loading,setLoading]=useState(true);const [updating,setUpdating]=useState(null);const [filter,setFilter]=useState('active');const [query,setQuery]=useState('')
  const load=useCallback(async()=>{setLoading(true);const client=requireSupabase();const {data,error}=await client.from('reservations').select('*').order('booking_date',{ascending:true}).order('booking_time',{ascending:true});if(error)toast.error(error.message);else setReservations(data||[]);setLoading(false)},[])
  useEffect(()=>{load();const client=requireSupabase();const channel=client.channel('admin-reservations').on('postgres_changes',{event:'INSERT',schema:'public',table:'reservations'},payload=>setReservations(current=>current.some(r=>r.id===payload.new.id)?current:[payload.new,...current])).on('postgres_changes',{event:'UPDATE',schema:'public',table:'reservations'},payload=>setReservations(current=>current.map(r=>r.id===payload.new.id?payload.new:r))).subscribe();return()=>{client.removeChannel(channel)}},[load])
  async function action(id,status){setUpdating(id);const {error}=await requireSupabase().from('reservations').update({status}).eq('id',id);if(error)toast.error(error.message);else toast.success(`Reservation marked ${status}.`);setUpdating(null)}
  const today=new Date().toLocaleDateString('en-CA');const todays=reservations.filter(r=>r.booking_date===today);const tableStatuses=Object.fromEntries(todays.filter(r=>activeStatuses.includes(r.status)).map(r=>[r.table_number,['arrived','occupied'].includes(r.status)?'occupied':'reserved']))
  const visible=useMemo(()=>reservations.filter(r=>(filter==='all'||(filter==='active'&&activeStatuses.includes(r.status))||r.status===filter)&&`${r.customer_name} ${r.reservation_id} ${r.phone}`.toLowerCase().includes(query.toLowerCase())),[reservations,filter,query])
  const stats=[['Today',todays.length,CalendarCheck],['Awaiting',todays.filter(r=>r.status==='pending').length,Clock3],['Occupied',Object.values(tableStatuses).filter(s=>s==='occupied').length,UsersRound]]
  return <div className="min-h-screen bg-[#0b0d0a]"><header className="border-b border-white/[.08] bg-panel/80 backdrop-blur"><div className="shell flex h-20 items-center justify-between"><Brand/><div className="flex items-center gap-3"><span className="hidden text-xs text-muted sm:block">{user?.email}</span><button onClick={()=>requireSupabase().auth.signOut()} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-muted hover:text-cream" aria-label="Sign out"><LogOut size={17}/></button></div></div></header><main className="shell py-8"><div className="flex items-center gap-3"><LayoutDashboard className="text-lime"/><div><h1 className="font-display text-3xl">Service overview</h1><p className="text-xs text-muted">Live restaurant operations · {new Date().toLocaleDateString('en-IN',{dateStyle:'full'})}</p></div></div>
  <div className="mt-7 grid gap-4 sm:grid-cols-3">{stats.map(([t,n,Icon])=><div className="card flex items-center justify-between p-5" key={t}><div><p className="text-xs text-muted">{t}</p><strong className="mt-1 block text-3xl">{n}</strong></div><Icon className="text-lime"/></div>)}</div>
  <div className="mt-7 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><aside className="card h-fit p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-lime">Live floor</p><h2 className="mt-1 font-display text-2xl">Table status</h2></div><span className="flex items-center gap-2 text-[10px] text-emerald-300"><i className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Realtime</span></div><div className="mt-5"><TableGrid statuses={tableStatuses} compact/></div><div className="mt-5"><TableLegend/></div></aside>
  <section className="card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-lime">Reservations</p><h2 className="mt-1 font-display text-2xl">Guest list</h2></div><button onClick={load} className="flex items-center gap-2 self-start text-xs text-muted hover:text-lime"><RefreshCw size={14}/>Refresh</button></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><div className="flex gap-2 overflow-x-auto">{['active','pending','confirmed','completed','cancelled','all'].map(f=><button onClick={()=>setFilter(f)} key={f} className={`rounded-full px-3 py-2 text-[11px] font-semibold capitalize ${filter===f?'bg-lime text-ink':'border border-white/10 text-muted'}`}>{f}</button>)}</div><label className="relative sm:ml-auto"><Search className="absolute left-3 top-2.5 text-muted" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-9 rounded-full border border-white/10 bg-white/[.03] pl-9 pr-4 text-xs outline-none focus:border-lime/50" placeholder="Search guest"/></label></div>
  {loading?<div className="grid h-60 place-items-center text-sm text-muted">Loading reservations…</div>:<div className="mt-5 grid gap-3 md:grid-cols-2">{visible.map(r=><ReservationCard key={r.id} reservation={r} onAction={action} updating={updating===r.id}/>)}</div>}{!loading&&!visible.length&&<div className="grid h-52 place-items-center text-center text-sm text-muted"><div><Check className="mx-auto mb-2 text-lime"/>Nothing here right now.</div></div>}</section></div></main></div>
}
