import { ArrowRight, CalendarCheck, Carrot, ChefHat, Leaf, Quote, Rocket, ShieldCheck, ShoppingBag, Sparkles, Star, UsersRound } from 'lucide-react'
import { useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import { menuItems } from '../data/menu'

const signatures=[menuItems[7],menuItems[4],menuItems[3]]
const promises=[
  [Carrot,'Fresh ingredients','Bright produce, carefully chosen and prepared fresh for every service.','bg-[#23301F]','Daily sourced'],
  [Leaf,'100% vegetarian','A generous menu where vegetables are always the main event.','bg-[#312A18]','Pure veg kitchen'],
  [Rocket,'Fast delivery','Restaurant favourites packed fresh and sent without the long wait.','bg-[#35231B]','Hot & carefully packed'],
  [UsersRound,'Family friendly','Comfort, familiar flavours and room for every generation.','bg-[#302120]','All ages welcome'],
  [Star,'Premium quality','Thoughtful details from the first ingredient to the final garnish.','bg-[#242238]','Chef checked'],
  [CalendarCheck,'Easy reservations','Live table selection in a booking flow that takes under a minute.','bg-[#1E302D]','20 live tables'],
]
const testimonials=[
  ['“A proper family place—bright flavours, warm service, zero fuss.”','The family regulars','bg-[#332B18]'],
  ['“The kind of vegetarian food that makes everyone order one more plate.”','Weekend guests','bg-[#22301F]'],
  ['“Fast, cheerful and genuinely memorable. Our new comfort-food stop.”','Local food lovers','bg-[#35231F]'],
]

export default function Home(){
  const heroRef=useRef(null)
  useEffect(()=>{const element=heroRef.current;if(!element||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame;const update=()=>{frame=null;const p=Math.min(window.scrollY/Math.max(element.offsetHeight,1),1);element.style.setProperty('--hero-scale',String(p*.08));element.style.setProperty('--hero-shift',`${p*34}px`);element.style.setProperty('--ingredient-up',`${p*-42}px`);element.style.setProperty('--ingredient-down',`${p*38}px`)};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();window.addEventListener('scroll',onScroll,{passive:true});return()=>{window.removeEventListener('scroll',onScroll);if(frame)cancelAnimationFrame(frame)}},[])
  return <div className="page-canvas">
    <section ref={heroRef} className="dark-surface relative min-h-[900px] overflow-hidden bg-[#171713] pt-28 lg:min-h-screen">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_42%,rgba(230,184,74,.22),transparent_32%),radial-gradient(circle_at_10%_80%,rgba(200,92,61,.16),transparent_30%)]"/>
      <div className="cinema-grain absolute inset-0 opacity-40"/>
      <span style={{'--ingredient-shift':'var(--ingredient-up)','--ingredient-rotate':'-12deg'}} className="hero-ingredient absolute right-[12%] top-[18%] hidden rounded-full border-2 border-white/30 bg-lime px-4 py-2 text-xs font-black uppercase tracking-widest lg:block">Mint · Herbs · Fresh</span>
      <span style={{'--ingredient-shift':'var(--ingredient-down)','--ingredient-rotate':'8deg'}} className="hero-ingredient absolute bottom-[18%] left-[46%] hidden rounded-full border-2 border-white/30 bg-terracotta px-4 py-2 text-xs font-black uppercase tracking-widest lg:block">Corn · Chilli · Flame</span>
      <div className="shell relative grid min-h-[790px] items-center gap-6 py-14 lg:grid-cols-[.92fr_1.08fr]">
        <div className="relative z-10 max-w-2xl">
          <p className="mb-6 inline-block rotate-[-1deg] border-2 border-ink bg-amber-300 px-4 py-2 text-[10px] font-black uppercase tracking-[.22em] text-ink shadow-[4px_4px_0_#FDFBF7]">Corn Bite Family Restro & Café</p>
          <h1 className="font-display text-6xl font-bold leading-[.82] tracking-[-.045em] sm:text-8xl lg:text-[7.1rem]"><span className="block">Fresh.</span><span className="block text-amber-300">Pure.</span><span className="block italic text-orange-300">Memorable.</span></h1>
          <h2 className="mt-7 max-w-xl font-display text-3xl font-semibold leading-tight sm:text-4xl">Where Every Meal Feels Like Home.</h2>
          <p className="mt-5 max-w-xl text-sm font-medium leading-7 text-cream/75 sm:text-base">Premium vegetarian dining with authentic flavours, quick food ordering and seamless table reservations.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Link to="/order" className="btn-warm"><ShoppingBag size={17}/>Order food</Link><Link to="/reserve" className="btn-primary"><CalendarCheck size={17}/>Reserve table</Link><Link to="/menu" className="btn-ghost">Explore menu</Link></div>
          <div className="mt-10 flex flex-wrap gap-3 text-xs font-bold"><span className="rounded-lg border-2 border-white/35 px-3 py-2">100% vegetarian</span><span className="rounded-lg border-2 border-white/35 px-3 py-2">Family dining</span><span className="rounded-lg border-2 border-white/35 px-3 py-2">Order online</span></div>
        </div>
        <div className="relative -mx-10 min-h-[430px] sm:min-h-[580px] lg:-mr-28 lg:min-h-[700px]">
          <div className="absolute inset-[10%] rounded-full bg-amber-300/20 blur-[80px]"/>
          <img src="/images/cinematic-paneer-hero.webp" alt="Luxury vegetarian platter with paneer, corn and fresh vegetables" className="hero-food absolute inset-0 h-full w-full object-contain"/>
          <div className="absolute bottom-12 right-10 rotate-2 border-[3px] border-white/70 bg-cream px-5 py-4 text-cream shadow-[7px_7px_0_#E6B84A] sm:right-20"><p className="text-[9px] font-black uppercase tracking-[.2em] text-amber-300">Chef’s platter</p><strong className="font-display text-2xl">Made to remember.</strong></div>
        </div>
      </div>
    </section>

    <div className="overflow-hidden border-y-[3px] border-ink bg-amber-300 py-4"><div className="marquee-track flex gap-9 whitespace-nowrap text-sm font-black uppercase tracking-[.15em]">{[0,1].flatMap(copy=>['Fresh every day','100% vegetarian','Order online','Reserve your table','Made with love','Family restaurant'].map(item=><span key={`${copy}-${item}`} className="flex items-center gap-9">{item}<i className="h-2.5 w-2.5 rotate-45 bg-ink"/></span>))}</div></div>

    <section className="py-24 sm:py-32"><div className="shell">
      <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div data-cinema="left"><p className="eyebrow-warm">Our restaurant story</p><h2 className="font-display text-6xl font-bold leading-[.85] sm:text-7xl">Good food.<br/><em className="text-terracotta">Great company.</em></h2></div><p data-cinema="right" className="max-w-2xl text-lg font-medium leading-8 text-muted">Corn Bite is where expressive vegetarian cooking meets the easy warmth of a family table. Familiar food, brighter flavours, and hospitality that never tries too hard.</p></div>
      <div className="mt-16 grid gap-6 lg:grid-cols-12"><article data-cinema="left" className="brutal-card image-luxury relative min-h-[560px] overflow-hidden lg:col-span-7"><img src="https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1400&q=85" alt="Fresh vegetables and premium ingredients" loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-x-0 bottom-0 border-t-[3px] border-white/70 bg-cream p-7"><p className="text-xs font-black uppercase tracking-widest text-lime">Fresh ingredient philosophy</p><h3 className="mt-2 font-display text-4xl font-bold">Colour you can taste.</h3></div></article><div className="grid gap-6 lg:col-span-5"><article data-cinema="right" className="brutal-card neo-lift flex min-h-[255px] flex-col justify-between bg-[#2D2119] p-8"><div className="flex items-start justify-between"><ChefHat className="text-orange-300"/><span className="rounded-full border border-white/30 px-3 py-1 text-[9px] font-black uppercase tracking-widest">Real kitchen</span></div><div><p className="text-xs font-black uppercase tracking-widest text-orange-300">Chef’s promise</p><h3 className="mt-2 font-display text-4xl font-bold">Made, never assembled.</h3><p className="mt-4 max-w-sm text-sm leading-6 text-cream/65">Every gravy, wok toss and garnish is prepared with intention—not pulled from a production line.</p></div></article><article data-cinema="right" className="brutal-card neo-lift min-h-[280px] bg-[#243421] p-8 text-white"><Quote className="text-amber-300" size={38}/><blockquote className="mt-8 font-display text-4xl font-semibold leading-tight">Food feels special when care is the first ingredient.</blockquote><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-amber-300">— The Corn Bite kitchen</p></article></div></div>
    </div></section>

    <section className="border-y-[3px] border-ink bg-[#F4EEDC] py-24 sm:py-28"><div className="shell"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow-warm">Signature dishes</p><h2 className="font-display text-6xl font-bold leading-[.9]">Plates worth<br/>talking about.</h2></div><Link to="/order" className="btn-warm">Order from the full menu <ArrowRight size={17}/></Link></div><div className="mt-14 grid gap-8 lg:grid-cols-3">{signatures.map((dish,index)=><article key={dish.name} data-cinema style={{'--cinema-delay':`${index*90}ms`}} className="brutal-card neo-lift image-luxury overflow-hidden"><div className="relative aspect-[4/3] overflow-hidden border-b-[3px] border-ink"><img src={dish.image} alt={dish.name} loading="lazy" className="h-full w-full object-cover"/><span className="absolute right-4 top-4 border-2 border-ink bg-amber-300 px-3 py-1.5 text-sm font-black">₹{dish.price}</span></div><div className="p-6"><span className="text-[10px] font-black uppercase tracking-[.2em] text-terracotta">{dish.category}</span><h3 className="mt-2 font-display text-3xl font-bold">{dish.name}</h3><p className="mt-3 text-sm leading-6 text-muted">{dish.description}</p></div></article>)}</div></div></section>

    <section className="py-24 sm:py-32"><div className="shell"><div className="max-w-3xl"><p className="eyebrow-warm">Why choose us</p><h2 className="font-display text-6xl font-bold leading-[.88] sm:text-7xl">Big standards.<br/><em className="text-lime">Zero stiffness.</em></h2></div><div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{promises.map(([Icon,title,text,color,stamp],index)=><article key={title} data-cinema style={{'--cinema-delay':`${index*60}ms`}} className={`brutal-card neo-lift flex min-h-[270px] flex-col p-7 ${color}`}><div className="flex items-start justify-between"><span className="grid h-13 w-13 place-items-center rounded-xl border-[3px] border-white/70 bg-black/20 p-3 text-amber-300"><Icon/></span><strong className="font-display text-3xl text-white/40">0{index+1}</strong></div><span className="mt-8 w-fit rounded-full border border-white/30 bg-black/15 px-3 py-1 text-[9px] font-black uppercase tracking-[.16em] text-amber-300">{stamp}</span><h3 className="mt-auto pt-6 font-display text-3xl font-bold">{title}</h3><p className="mt-3 text-sm font-medium leading-6 text-cream/65">{text}</p></article>)}</div></div></section>

    <section className="border-y-[3px] border-white/20 bg-[#171713] py-24 text-cream"><div className="shell"><p className="eyebrow-warm text-amber-300">Guest notes</p><h2 className="font-display text-6xl font-bold">Passed around the table.</h2><div className="mt-14 grid gap-8 md:grid-cols-3">{testimonials.map(([quote,by,color])=><article key={by} data-cinema className={`sticky-note border-[3px] border-white/70 p-7 text-cream shadow-[8px_8px_0_#E6B84A] transition hover:-translate-y-2 ${color}`}><div className="mb-14 flex gap-1">{[1,2,3,4,5].map(n=><Star key={n} size={16} className="fill-amber-300 text-amber-300"/>)}</div><blockquote className="font-display text-3xl font-semibold leading-tight">{quote}</blockquote><p className="mt-6 text-xs font-black uppercase tracking-widest text-amber-300">— {by}</p></article>)}</div></div></section>

    <section className="py-24"><div className="shell"><div data-cinema="scale" className="brutal-card relative overflow-hidden bg-[#2B1813] px-7 py-16 text-center text-white sm:px-12 sm:py-20"><div className="absolute -left-16 -top-16 h-48 w-48 rounded-full border-[28px] border-orange-400/20"/><div className="absolute -bottom-20 -right-12 h-56 w-56 rotate-12 border-[3px] border-amber-300/20"/><Sparkles className="relative mx-auto text-amber-300"/><p className="relative mt-6 text-xs font-black uppercase tracking-[.22em] text-orange-300">Your table is waiting</p><h2 className="relative mx-auto mt-5 max-w-4xl font-display text-6xl font-bold leading-[.88] sm:text-7xl">Come hungry.<br/>Leave with a story.</h2><p className="relative mx-auto mt-6 max-w-xl font-medium leading-7 text-white/70">Choose your moment, select your table, and let us take care of everything that follows.</p><div className="relative mx-auto mt-7 flex w-fit flex-wrap justify-center gap-2 text-[10px] font-black uppercase tracking-widest"><span className="rounded-full border border-white/30 px-3 py-2">Dine in</span><span className="rounded-full border border-white/30 px-3 py-2">Pickup</span><span className="rounded-full border border-white/30 px-3 py-2">Delivery</span></div><div className="relative mt-8 flex flex-wrap justify-center gap-3"><Link to="/reserve" className="btn-ghost"><CalendarCheck size={17}/>Reserve table</Link><Link to="/order" className="btn-primary"><ShoppingBag size={17}/>Order food</Link></div></div></div></section>
  </div>
}
