import { ArrowLeft, LockKeyhole, Mail, Sprout } from 'lucide-react'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { Link, useNavigate } from 'react-router-dom'
import { isSupabaseConfigured, requireSupabase } from '../lib/supabase'

export default function Login() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const navigate=useNavigate()
  async function submit(e){e.preventDefault();setLoading(true);try{const client=requireSupabase();const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;const {data:admin,error:roleError}=await client.rpc('is_admin');if(roleError||!admin){await client.auth.signOut();throw new Error('This account is not authorized for restaurant administration.')}navigate('/admin')}catch(error){toast.error(error.message)}finally{setLoading(false)}}
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="relative hidden overflow-hidden lg:block"><img src="/images/restaurant-hero.png" className="absolute inset-0 h-full w-full object-cover" alt="Corn Bite dining room"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/30 to-transparent"/><div className="absolute bottom-12 left-12 max-w-md"><p className="eyebrow">Restaurant operations</p><h1 className="font-display text-5xl">Hospitality, with a clear view.</h1><p className="mt-4 text-sm leading-6 text-cream/65">Live reservations, table occupancy and guest flow—all in one calm workspace.</p></div></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-md"><Link to="/" className="mb-12 inline-flex items-center gap-2 text-sm text-muted hover:text-lime"><ArrowLeft size={16}/>Back to restaurant</Link><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-lime text-ink"><Sprout/></span><div><h2 className="font-display text-3xl">Welcome back</h2><p className="text-xs text-muted">Authorized team members only</p></div></div>{!isSupabaseConfigured&&<div className="mt-7 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-200">Add Supabase credentials to your .env file before signing in.</div>}<form onSubmit={submit} className="mt-8 space-y-5"><label><span className="label">Email</span><div className="relative"><Mail size={17} className="absolute left-4 top-3.5 text-muted"/><input className="input pl-11" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@cornbite.com"/></div></label><label><span className="label">Password</span><div className="relative"><LockKeyhole size={17} className="absolute left-4 top-3.5 text-muted"/><input className="input pl-11" type="password" required minLength="8" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></div></label><button disabled={loading||!isSupabaseConfigured} className="btn-primary w-full">{loading?'Verifying…':'Sign in securely'}</button></form><p className="mt-6 text-center text-xs text-muted">Access is logged and protected by Supabase Auth + RLS.</p></div></section></main>
}
