import { ArrowRight, Bike, Coffee, CookingPot, Cookie, GlassWater, LayoutGrid, Minus, Pizza, Plus, Search, Sandwich, ShoppingBag, Soup, Store, Trash2, UtensilsCrossed } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useCart } from '../context/CartContext'
import { orderCategories, orderMenuItems } from '../data/orderMenu'
import { useMenuAvailability } from '../hooks/useMenuAvailability'

const categoryIcons={Chinese:Soup,Beverages:Coffee,Pizza,'Mumbai Special Sigri Dosa':CookingPot,Sandwich,'Sweet Corn Cup':GlassWater,'Pav Bhaji':UtensilsCrossed,Fries:Cookie,Burgers:Sandwich}

function CartPanel({items,itemCount,subtotal,setQuantity,removeItem}) {
  return <aside className="order-cart-panel flex h-[calc(100vh-112px)] min-h-[620px] flex-col rounded-2xl border-[3px] border-amber-300 bg-[#191713] shadow-[7px_7px_0_#E6B84A]">
    <div className="border-b border-white/[.07] p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-orange-400">Current order</p><h2 className="mt-1 font-display text-2xl">Your cart</h2></div><span className="grid h-10 min-w-10 place-items-center rounded-full bg-orange-400/10 px-3 text-sm font-bold text-orange-300">{itemCount}</span></div>
      <div className="mt-5 grid grid-cols-2 gap-2 rounded-xl bg-black/20 p-1"><span className="flex items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-orange-500 to-amber-300 px-3 py-2 text-xs font-bold text-[#1b1008]"><Bike size={14}/>Delivery</span><span className="flex items-center justify-center gap-2 px-3 py-2 text-xs text-muted"><Store size={14}/>Pickup</span></div><p className="mt-3 text-[11px] leading-5 text-muted">Choose delivery or pickup and enter your address during checkout.</p>
    </div>
    {!items.length?<div className="grid flex-1 place-items-center px-8 text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-orange-400/10 text-orange-300"><ShoppingBag/></span><h3 className="mt-5 font-display text-2xl">Ready when you are.</h3><p className="mt-2 text-sm leading-6 text-muted">Add dishes from the menu to begin your order.</p></div></div>:<div className="order-page-scrollbar flex-1 space-y-3 overflow-y-auto p-5">{items.map(item=><article key={item.id} className="rounded-2xl border border-white/[.07] bg-white/[.035] p-3"><div className="flex gap-3"><img src={item.image} alt="" className="h-16 w-16 shrink-0 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="line-clamp-2 text-sm font-semibold leading-5">{item.name}</h3><button onClick={()=>removeItem(item.id)} className="shrink-0 text-muted transition hover:text-red-300" aria-label={`Remove ${item.name}`}><Trash2 size={14}/></button></div><div className="mt-2 flex items-center justify-between"><strong className="text-sm text-amber-300">₹{item.price*item.quantity}</strong><div className="inline-flex items-center rounded-full border border-white/10 bg-black/15"><button onClick={()=>setQuantity(item.id,item.quantity-1)} className="grid h-7 w-7 place-items-center" aria-label={`Decrease ${item.name}`}><Minus size={11}/></button><span className="w-6 text-center text-xs">{item.quantity}</span><button onClick={()=>setQuantity(item.id,item.quantity+1)} className="grid h-7 w-7 place-items-center" aria-label={`Increase ${item.name}`}><Plus size={11}/></button></div></div></div></div></article>)}</div>}
    <div className="border-t border-white/[.08] p-6"><div className="space-y-2 text-sm"><div className="flex justify-between text-muted"><span>Subtotal</span><span>₹{subtotal}</span></div><div className="flex justify-between text-muted"><span>Delivery charge</span><span>Calculated later</span></div><div className="mt-3 flex justify-between border-t border-white/[.08] pt-4 text-lg"><strong>Total</strong><strong className="text-amber-300">₹{subtotal}</strong></div></div><Link to={items.length?'/checkout':'/order'} className={`mt-5 flex h-12 items-center justify-center gap-2 rounded-full text-sm font-bold transition ${items.length?'bg-gradient-to-r from-orange-500 to-amber-300 text-[#1b1008] shadow-[0_12px_35px_rgba(245,158,11,.18)] hover:-translate-y-0.5':'pointer-events-none bg-white/5 text-muted'}`}>Continue to checkout <ArrowRight size={16}/></Link></div>
  </aside>
}

export default function OrderMenu() {
  const [category,setCategory]=useState('Chinese');const [query,setQuery]=useState('');const {addItem,items,itemCount,subtotal,setQuantity,removeItem,setIsOpen}=useCart()
  const {isItemAvailable,loading:availabilityLoading,error:availabilityError}=useMenuAvailability()
  const visibleItems=useMemo(()=>orderMenuItems.filter(item=>(category==='All'||item.category===category)&&item.name.toLowerCase().includes(query.trim().toLowerCase())),[category,query])
  const counts=useMemo(()=>Object.fromEntries(orderCategories.map(value=>[value,orderMenuItems.filter(item=>item.category===value).length])),[])

  return <main className="dark-surface min-h-screen bg-[#171713] pb-24 pt-[88px] text-cream lg:pb-8">
    <div className="border-b border-white/[.07] bg-[radial-gradient(circle_at_70%_0%,rgba(249,115,22,.12),transparent_32%)]"><div className="mx-auto max-w-[1520px] px-4 py-8 sm:px-7 lg:px-8"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.24em] text-orange-400">Corn Bite delivery</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">What are you craving?</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Fresh vegetarian favourites for delivery or restaurant pickup.</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-xs text-muted"><strong className="text-cream">76</strong> menu items</span><span className="rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-xs text-muted">100% vegetarian</span></div></div></div></div>
    <div className="mx-auto grid max-w-[1520px] gap-6 px-4 py-6 sm:px-7 lg:grid-cols-[210px_minmax(0,1fr)_350px] lg:px-8">
      <aside className="hidden lg:block"><div className="sticky top-[100px] rounded-[1.5rem] border border-white/[.08] bg-[#161410] p-3"><div className="px-3 pb-3 pt-2"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-muted">Categories</p></div><div className="order-page-scrollbar max-h-[calc(100vh-160px)] space-y-1 overflow-y-auto">{['All',...orderCategories].map(value=>{const Icon=value==='All'?LayoutGrid:categoryIcons[value]||UtensilsCrossed;return <button key={value} onClick={()=>setCategory(value)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition ${category===value?'bg-gradient-to-r from-orange-500/20 to-amber-300/10 text-amber-200':'text-muted hover:bg-white/[.04] hover:text-cream'}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${category===value?'bg-orange-400 text-[#1b1008]':'bg-white/[.05]'}`}><Icon size={16}/></span><span className="min-w-0 flex-1 truncate text-xs font-semibold">{value}</span><span className="text-[10px] opacity-50">{value==='All'?orderMenuItems.length:counts[value]}</span></button>})}</div></div></aside>
      <section className="min-w-0"><div className="sticky top-[76px] z-20 -mx-1 bg-[#0d0c0a]/95 px-1 pb-4 backdrop-blur-xl"><label className="relative block"><Search className="absolute left-4 top-3.5 text-muted" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} className="h-12 w-full rounded-2xl border border-white/10 bg-[#1a1814] pl-11 pr-4 text-sm outline-none transition placeholder:text-muted/50 focus:border-orange-400/50 focus:ring-2 focus:ring-orange-400/10" placeholder="Search the complete menu" aria-label="Search order menu"/></label><div className="mt-3 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] lg:hidden">{['All',...orderCategories].map(value=><button key={value} onClick={()=>setCategory(value)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${category===value?'bg-orange-400 text-[#1b1008]':'border border-white/10 text-muted'}`}>{value}</button>)}</div></div>
        <div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-orange-400">{category==='All'?'Complete menu':category}</p><h2 className="mt-1 font-display text-3xl">Choose your dishes</h2></div><span className="text-xs text-muted">{availabilityLoading?'Checking availability…':`${visibleItems.filter(item=>isItemAvailable(item.id)).length} available`}</span></div>
        {availabilityError&&<div className="mb-4 rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-3 text-xs text-amber-200">Live availability could not be refreshed. Ordering will still be verified at checkout.</div>}
        <div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{visibleItems.map((item,index)=>{const available=isItemAvailable(item.id);return <article key={`${category}-${item.id}`} style={{'--menu-delay':`${(index%6)*40}ms`}} className={`menu-card-enter group rounded-[1.4rem] border bg-[#181612] p-3 transition duration-300 ${available?'border-white/[.08] hover:-translate-y-1 hover:border-orange-400/25':'border-white/[.05] opacity-55 grayscale'}`}><div className="relative aspect-[16/10] overflow-hidden rounded-[1rem]"><img src={item.image} alt="" loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/45 to-transparent"/><span className="absolute left-3 top-3 rounded-full bg-black/55 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.14em] text-amber-200">{item.category}</span><span className={`absolute right-3 top-3 rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wide ${available?'bg-emerald-500/90 text-white':'bg-red-500/90 text-white'}`}>{available?'Available':'Currently unavailable'}</span></div><div className="px-1 pb-1 pt-4"><h3 className="min-h-12 font-display text-xl leading-6">{item.name}</h3><div className="mt-3 flex items-center justify-between gap-3"><strong className={available?'text-lg text-amber-300':'text-xs text-red-300'}>{available?`₹${item.price}`:'Currently unavailable'}</strong><button disabled={!available||availabilityLoading} onClick={()=>{if(available)addItem(item,false)}} className={`inline-flex h-10 items-center gap-2 rounded-full px-4 text-xs font-bold transition ${available?'bg-white/[.07] text-cream hover:bg-gradient-to-r hover:from-orange-500 hover:to-amber-300 hover:text-[#1b1008]':'cursor-not-allowed bg-white/[.04] text-white/30'}`} aria-label={available?`Add ${item.name} for ₹${item.price}`:`${item.name} currently unavailable`}><Plus size={14}/>{available?'Add':'Unavailable'}</button></div></div></article>})}</div>
        {!visibleItems.length&&<div className="rounded-3xl border border-white/[.08] bg-white/[.025] py-20 text-center"><Search className="mx-auto text-orange-400"/><h3 className="mt-5 font-display text-2xl">No dishes found.</h3><button onClick={()=>{setQuery('');setCategory('All')}} className="mt-4 text-sm font-bold text-amber-300">Clear search</button></div>}
      </section>
      <div className="hidden lg:block"><div className="sticky top-[100px]"><CartPanel items={items} itemCount={itemCount} subtotal={subtotal} setQuantity={setQuantity} removeItem={removeItem}/></div></div>
    </div>
    <button onClick={()=>setIsOpen(true)} className={`fixed bottom-4 left-4 right-4 z-40 flex items-center justify-between rounded-2xl bg-gradient-to-r from-orange-500 to-amber-300 px-5 py-4 text-[#1b1008] shadow-[0_18px_60px_rgba(0,0,0,.45)] lg:hidden ${itemCount?'':'pointer-events-none translate-y-24'}`}><span className="flex items-center gap-3"><span className="grid h-7 min-w-7 place-items-center rounded-full bg-black/15 px-2 text-xs font-bold">{itemCount}</span><strong className="text-sm">View cart</strong></span><strong>₹{subtotal}</strong></button>
  </main>
}
